<a href="https://colab.research.google.com/github/24cse150rishirajsahu/DMDW-lab-assignment-/blob/main/ASSG4DMDW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
data = pd.DataFrame({
    'Color': ['Red', 'Red', 'Blue', 'Green'],
    'Size': ['Small', 'Medium', 'Large', 'Medium'],
    'Purchased': [1, 1, 0, 1]
})

def nominal_dissimilarity(data, columns):
    n = len(data)
    matrix = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            mismatches = sum(data.loc[i, col] != data.loc[j, col]
                             for col in columns)
            matrix[i, j] = mismatches / len(columns)

    return matrix

def ordinal_dissimilarity(data, column, order):
    ranks = {value: i for i, value in enumerate(order)}
    normalized = data[column].map(ranks) / (len(order) - 1)

    n = len(data)
    matrix = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            matrix[i, j] = abs(normalized.iloc[i] - normalized.iloc[j])

    return matrix
def binary_dissimilarity(data, column):
    n = len(data)
    matrix = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            a = data.loc[i, column]
            b = data.loc[j, column]

            if a == 1 and b == 1:
                matrix[i, j] = 0
            elif a != b:
                matrix[i, j] = 1
            else:
                matrix[i, j] = 0

    return matrix
nominal_matrix = nominal_dissimilarity(data, ['Color'])

ordinal_matrix = ordinal_dissimilarity(
    data,
    'Size',
    ['Small', 'Medium', 'Large']
)

binary_matrix = binary_dissimilarity(data, 'Purchased')

print("Nominal Dissimilarity Matrix:")
print(nominal_matrix)

print("\nOrdinal Dissimilarity Matrix:")
print(ordinal_matrix)

print("\nBinary Dissimilarity Matrix:")
print(binary_matrix)


Nominal Dissimilarity Matrix:
[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]

Ordinal Dissimilarity Matrix:
[[0.  0.5 1.  0.5]
 [0.5 0.  0.5 0. ]
 [1.  0.5 0.  0.5]
 [0.5 0.  0.5 0. ]]

Binary Dissimilarity Matrix:
[[0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 1. 0. 1.]
 [0. 0. 1. 0.]]


In [7]:
import pandas as pd
import numpy as np
print("nominal dataset")
print(data)

n = len(data)
matrix = np.zeros((n, n))

for i in range(n):
    for j in range(n):
        count = 0
        for col in data.columns:
            if data.loc[i, col] != data.loc[j, col]:
                count += 1
        matrix[i, j] = count / len(data.columns)

print("\n DISSIMILARITY MATRIX  - NOMINAL")
print(pd.DataFrame(
    matrix,
    index=['01', '02', '03', '04'],
    columns=['01', '02', '03', '04']
).round(2))
print("\n")

nominal dataset
   Color    Size  Purchased
0    Red   Small          1
1    Red  Medium          1
2   Blue   Large          0
3  Green  Medium          1

 DISSIMILARITY MATRIX  - NOMINAL
      01    02   03    04
01  0.00  0.33  1.0  0.67
02  0.33  0.00  1.0  0.33
03  1.00  1.00  0.0  1.00
04  0.67  0.33  1.0  0.00




In [9]:
import pandas as pd
import numpy as np

data =pd.DataFrame({
    'student' : [1,1,0,0],
    'Employed' : [0,1,1,0],
    'purchased': [1,1,0,1]
})

print("BINARY DATASET")
print(data)

n = len(data)
matrix = np.zeros((n,n))

for i in range(n):
  for j in range(n):

    diff = 0

    for col in data.columns:
      if data.loc[i,col] != data.loc[j,col]:
        diff += 1

    matrix[i,j] = diff / len(data.columns)
print("\nDISSIMILARITY MATRIX - BINARY")
print(pd.DataFrame(
    matrix,
    index = ['01','02','03','04'],
    columns = ['01','02','03','04']
).round(2)
)

BINARY DATASET
   student  Employed  purchased
0        1         0          1
1        1         1          1
2        0         1          0
3        0         0          1

DISSIMILARITY MATRIX - BINARY
      01    02    03    04
01  0.00  0.33  1.00  0.33
02  0.33  0.00  0.67  0.67
03  1.00  0.67  0.00  0.67
04  0.33  0.67  0.67  0.00


In [11]:
import pandas as pd
import numpy as np

data =pd.DataFrame({
    'satisfaction': ['Low','medium','high','medium']
})

print("ORDINAL DATASET")
print(data)

rank ={
    'low': 0,
    'medium': 1,
    'high': 2
}

n = len(data)
matrix = np.zeros((n,n))

for i in range(n):
  for j in range(n):

    x = rank[data.loc[i,'satisfaction'].lower()]
    y = rank[data.loc[j,'satisfaction'].lower()]

    matrix[i,j] = abs(x-y)/2

print("\nDISSIMILARITY MATRIX - ORDINAL")
print(pd.DataFrame(
    matrix,
    index = ['01','02','03','04'],
    columns = ['01','02','03','04']
).round(2))

ORDINAL DATASET
  satisfaction
0          Low
1       medium
2         high
3       medium

DISSIMILARITY MATRIX - ORDINAL
     01   02   03   04
01  0.0  0.5  1.0  0.5
02  0.5  0.0  0.5  0.0
03  1.0  0.5  0.0  0.5
04  0.5  0.0  0.5  0.0
